spring:
  datasource:
    url: jdbc:mysql://kavic.xyz:3306/course
    username: course
    password: adminkavic
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      continue-on-error: true  # 添加这一行

  jpa:
    hibernate:
      ddl-auto: update  # 自动更新表结构
    show-sql: true      # 显示SQL语句
    properties:
      hibernate:
        format_sql: true  # 格式化SQL
#        dialect: org.hibernate.dialect.MySQL5Dialect